# Generated by Django 3.1.4 on 2021-04-21 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('full_name', models.CharField(max_length=100)),
                ('block', models.CharField(max_length=2)),
                ('room_no', models.IntegerField()),
                ('cycles_remaining', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UseCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_clothes', models.CharField(choices=[('1-5', (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'))), ('6-10', (('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'))), ('11-15', (('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'))), ('16-20', (('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')))], max_length=6)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('collection_info', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
