# Generated by Django 3.1.4 on 2021-04-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=9)),
                ('full_name', models.CharField(max_length=25)),
                ('cycles_needed', models.IntegerField()),
            ],
        ),
    ]
