# Generated by Django 3.1.7 on 2021-03-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecycle',
            name='collection_info',
            field=models.DateTimeField(null=True),
        ),
    ]
